package com.example.nick.insulinpump;

public enum ErrorType{
    LOW_BATTERY, SENSOR_FAILURE, PUMP_FAILURE, DELIVERY_FAILURE, NEEDLE_ASSMBLY_REMOVED, INSULIN_RESERVOIR_REMOVED, SUGAR_LOW, SUGAR_OK, SUGAR_HIGH, INSULIN_RESERVOIR_LOW
}
